# apiVersion: v1
# kind: Service
# metadata:
#   name: mongodb-service
#   namespace: mongo-namespace
# spec:
#   selector:
#     app: mongo
#   type: ClusterIP
#   ports:
#     - protocol: TCP
#       port: 27017
#       targetPort: 27017
  

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: mongo-namespace
spec:
  selector:
    app: mongo
  type: NodePort
  ports:
    - protocol: TCP
      port: 27017        # Port exposed inside the cluster
      targetPort: 27017  # Port the MongoDB container is listening on
      nodePort: 32000    # Port exposed on the node (optional, can be auto-assigned)
