apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: mongo-namespace
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/mongo-pv
