# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: webapp-deployment
#   labels:
#     app: webapp
#   namespace: mongo-namespace
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: webapp
#   template:
#     metadata:
#       labels:
#         app: webapp
#     spec:
#       containers:
#       - name: mongo-express
#         image: mongo-express:latest
#         ports:
#         - containerPort: 8081
#         resources:
#       requests:
#         memory: "512Mi"
#         cpu: "500m"
#       limits:
#         memory: "1Gi"
#         cpu: "1"
#         env:
#         - name: ME_CONFIG_MONGODB_ADMINUSERNAME
#           valueFrom:
#             secretKeyRef: 
#               name: secret 
#               key: mongo-user
#         - name: ME_CONFIG_MONGODB_ADMINPASSWORD
#           valueFrom: 
#             secretKeyRef:
#               name: secret
#               key: mongo-password 
#         - name: ME_CONFIG_MONGODB_SERVER
#           valueFrom: 
#             configMapKeyRef:
#               name: mongo-config
#               key: mongo-url


apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: mongo-namespace
  labels:
    app: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: mongo-express
        image: mongo-express:6.0
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef: 
              name: secret
              key: mongo-user
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom: 
            secretKeyRef:
              name: secret
              key: mongo-password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom: 
            configMapKeyRef:
              name: mongo-config
              key: mongo-url
