# apiVersion: v1
# kind: Service
# metadata:
#   name: webapp-service
#   namespace: mongo-namespace
# spec:
#   selector:
#     app: webapp
#   ports:
#     - protocol: TCP
#       port: 8081
#       targetPort: 8081
#       nodePort: 30200
  

apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: mongo-namespace
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30200  # Optional, Kubernetes can auto-assign this if omitted


